#!/bin/sh
show_menu(){
    NORMAL=`echo "\033[m"`
    MENU=`echo "\033[36m"` #Blue
    NUMBER=`echo "\033[33m"` #yellow
    FGRED=`echo "\033[41m"`
    RED_TEXT=`echo "\033[31m"`
    ENTER_LINE=`echo "\033[33m"`
    echo -e "${MENU}**********************APP MENU***********************${NORMAL}"
    echo -e "${MENU}**${NUMBER} 1)${MENU} Connect MYSQL ${NORMAL}"
    echo -e "${MENU}**${NUMBER} 2)${MENU} Import Data In HDFS ${NORMAL}"
    echo -e "${MENU}**${NUMBER} 3)${MENU} Import Data In HIVE ${NORMAL}"
    echo -e "${MENU}**${NUMBER} 4)${MENU} Show Data In HIVE ${NORMAL}"
    echo -e "${MENU}**${NUMBER} 5)${MENU} Pin Code ${NORMAL}"
    echo -e "${MENU}**${NUMBER} 6)${MENU} State ${NORMAL}"
    echo -e "${MENU}**${NUMBER} 7)${MENU} Area${NORMAL}"
    echo -e "${MENU}*********************************************${NORMAL}"
    echo -e "${ENTER_LINE}Please enter a menu option and enter or ${RED_TEXT}enter to exit. ${NORMAL}"
    read opt
}
function option_picked() {
    COLOR='\033[01;31m' # bold red
    RESET='\033[00;00m' # normal white
    MESSAGE=${@:-"${RESET}Error: No message passed"}
    echo -e "${COLOR}${MESSAGE}${RESET}"
}

clear
show_menu
while [ opt != '' ]
    do
    if [[ $opt = "" ]]; then 
            exit;
    else
        case $opt in
        1) clear;
        option_picked "To Connect to DB and Get all databases present: look for name test";
        sqoop list-databases --connect "jdbc:mysql://localhost" --username root --password root
        show_menu;
        ;;

        2) clear;
            option_picked "Now lets import the test DB in our hdfs file system ";
	    sqoop import --connect "jdbc:mysql://localhost/test" --username root --password root --table AppData --target-dir /tmp/temp
            show_menu;
            ;;

        3) clear;
            option_picked "Now We can import the test DB in our Hive table Structure to be able to Query";
            sqoop import --connect "jdbc:mysql://localhost/test" --username root --password root --table AppData -hive-import
            show_menu;
            ;;

        4) clear;
            option_picked "Going to show the Sample Data from imported Table";
	    hive -e "select *  from AppData where ID < 10"    
            show_menu;
            ;;
	5) clear;
            option_picked "Search Based on PinCode";
	    echo "Please Enter the Pin Code"
	    read pinCode
	    echo "PinCode is ${pinCode}"
	    echo "inThis PinCode what do you want to search"
	    echo "select One Among  1)Bank 2)Restaurant 3)Hospital 4)School 5) ShoppingMall "
	    read n
	    case $n in
		1)	echo "Please Enter the bank name"
			read bankName
			#getpinCodeBank $pinCode $bankName	
			hive -e "Select * from AppData where PinCode = $pinCode AND bank = '${bankName}'"
			;;				
		2) 	echo "Please Enter the Restaurant name"
			read resName
			#getpinCodeBank $pinCode $bankName	
			hive -e "Select * from AppData where PinCode = $pinCode AND restaurant = '${resName}'"
			;;
		3) 	echo "Please Enter the Hospital name"
			read hosName
			#getpinCodeBank $pinCode $bankName	
			hive -e "Select * from AppData where PinCode = $pinCode AND hospital = '${hosName}'"
			;;
		4) 	echo "Please Enter the school name"
			read schoolName
			#getpinCodeBank $pinCode $bankName	
			hive -e "Select * from AppData where PinCode = $pinCode AND School = '${schoolName}'"
			;;
		5) 	echo "Please Enter the Shopping Mall name"
			read mallName
			#getpinCodeBank $pinCode $bankName	
			hive -e "Select * from AppData where PinCode = $pinCode AND shoppimgmall = '${mallName}'"
			;;
		*) echo "Please Select one among the option[1-5]";;
	    esac
	    show_menu;
            ;;
	
	6) clear;
            option_picked "Search Based on State";
	    echo "Please Enter the State Name"
	    read stateName
	    echo "Entered StateName is ${stateName}"
	    echo "inThis State what do you want to search"
	    echo "select One Among  1)Address 2)Restaurant 3)Hospital 4)School 5) Bank "
	    read n
	    case $n in
		1)	echo "Please Enter the Address"
			read address
			#getpinCodeBank $pinCode $bankName	
			hive -e "Select * from AppData where state = $stateName AND Address = '${address}'"
			;;				
		2) 	echo "Please Enter the Restaurant name"
			read resName
			#getpinCodeBank $pinCode $bankName	
			hive -e "Select * from AppData where state = $stateName AND restaurant = '${resName}'"
			;;
		3) 	echo "Please Enter the Hospital name"
			read hosName
			#getpinCodeBank $pinCode $bankName	
			hive -e "Select * from AppData where state = $stateName AND hospital = '${hosName}'"
			;;
		4) 	echo "Please Enter the school name"
			read schoolName
			#getpinCodeBank $pinCode $bankName	
			hive -e "Select * from AppData where state = $stateName AND School = '${schoolName}'"
			;;
		*) echo "Please Select one among the option[1-5]";;
	    esac
	    show_menu;
            ;;

        x)exit;
        ;;

        \n)exit;
        ;;

        *)clear;
        option_picked "Pick an option from the menu";
        show_menu;
        ;;
    esac
fi

function getpinCodeBank(){
	echo "in getPinCodebank"
	echo $1
	echo $2
	hive -e "Select * from AppData where PinCode = $1 AND Bank = ${2}"
}

done
